@startuml 統合ドメインモデル図
skinparam componentStyle rectangle
skinparam linetype ortho


[ユーザー] o-- [管理者]
[ユーザー] o-- [顧客]


[管理者] o-- [管理アカウント]
[管理アカウント] o-- [メールアドレス]
[管理アカウント] o-- [名前]
[管理アカウント] o-- [パスワード]


[顧客] o-- [アカウント]
[アカウント] o-- [セッション]
[セッション] o-- [セッション状態]
[アカウント] o-- [メールアドレス]
[アカウント] o-- [名前]
[アカウント] o-- [パスワード]


[顧客] o-- [カート]
[カート] o-- [商品]
[管理者] o-- [商品]
[商品] o-- [商品価格]
[商品] o-- [商品説明]
[商品] o-- [商品名]


[顧客] o-- [注文]
[管理者] o-- [注文]
[注文] o-- [注文状態]
[注文] o-- [注文明細]
[注文明細] o-- [商品]
[注文] o-- [決済ログ]
[注文] o-- [配送]
[注文] o-- [返品]
[管理者] o-- [返品]

[管理者] o-- [出荷]
[出荷] o-- [配送]
[出荷] o-- [メール送信]
[配送] o-- [配送状態]

@enduml