@startuml .
skinparam linetype ortho
hide circle
' Entities
entity 図書 {
  + 管理番号 : String
  --
  + 書名 : String
  + 種類 : (書籍|雑誌)
}

entity 利用者 {
  + 会員番号 : String
  --
  + 氏名 : String
  + 種類 : (学生|教職員)
}

entity 貸出 {
  + 貸出日 : Date
  + 返却予定日 : Date
  + 貸出状況 : (貸出中|返却済み)
}

entity 予約 {
  + 予約日 : Date
  + 状態 : (未連絡|連絡済み)
}

' Relations
利用者 "1" -- "0..*" 貸出 : 貸出する
図書 "1" -- "0..*" 貸出 : 貸出される
利用者 "1" -- "0..*" 予約 : 予約する
図書 "1" -- "0..1" 予約 : 予約される
図書 "1" -- "0..*" 貸出履歴 : 記録される
利用者 "1" -- "0..*" 貸出履歴 : 記録される
貸出 "1" -- "1" 貸出履歴 : 記録される

' Note
note left of 図書
書籍は複数冊存在する可能性があるため、
管理番号で区別する。
end note

note right of 利用者
学生には雑誌の貸出、教職員の貸出冊数など、
ルールに違いがある。
end note
@enduml